### ISSUE TITLE
Annotation add_property type signature missing dict 

### ISSUE THREAD

**Issue by kelleyl** [clamsproject/mmif-python#144]
When addressing issue clamsproject/app-tesseractocr-wrapper#1, I used the annotation.add_property method to add a "text" property to an annotation with type TextDocument (see below). The value of this annotation is a dict. Currently, the type signature of the add_property method specifies that the value should be a string. This could be fixed by changing the type of `value` to `Union[str, dict]`. Thoughts? 
```json
{
"@type": "http://mmif.clams.ai/0.2.1/vocabulary/TextDocument", 
"properties":
     {"text": 
         {"@value": "WISCONSIN"},
     "id": "td180_1"}
}
```

**Comment by angus-lherrou** [comment]
Really, the value of a property can be any JSON object, so `dict`, `list`, `str`, `int`, `float`, or `bool`. That method can also accept `MmifObject`s, like the `Text` class.

Personally, I think `Union[str, dict, list, int, float, bool, MmifObject]` is a bit cumbersome, but I suppose it could be useful for developers to be as explicit as possible.

**Comment by keighrim** [comment]
I think for this specific case, you can use `Document` class instead of `Annotation` class to instantiate a document. `Document` class has necessary methods to add text to its property. 

For general cases, annotation/document properties defined in MMIF vocabulary are fairly well specified with their data types, we just didn't implement how to handle those information in python SDK (e.g. automatically parse vocab definitions and generate sub classes with tight type constraints). I don't think, though, we planned to allow properties to have really complex nested structures, except for that `text` property of a `TextDocument`. We still have properties that are lists of primitives. So I think we can use primitives (string, number, and booleans) and list of them, without actually posing constraints programatically, at least for now. @marcverhagen how do you think?

**Comment by keighrim** [comment]
#153 adds a very simple restriction to types of objects that can be used as properties of `Annotation` objects. We may have to revisit the restriction in the future, but for now this solution seems to be working with all annotations types we have in the vocab.
