### ISSUE TITLE
MMIF annotation getter doesn't work on short ids

### ISSUE THREAD

**Issue by haydenmccormick** [clamsproject/mmif-python#279]
### Bug Description

When using the native MMIF annotation getter `mmif[anno.id]`, the SDK throws a KeyError. When using view-scoped long ids (`mmif[anno.long_id]`), it works as expected.

### Reproduction steps

Using a MMIF file (version 1.0.4), try to access a given annotation via `mmif[id]`, where `id` is a short annotation ID.

### Expected behavior

```
>>> for anno in mmif["v_0"].annotations:
...     anno = mmif[anno.id]
```

Should successfully access a MMIF Annotation object in each iteration

### Log output

```shell
>>> with open("spacy1.mmif", "r") as f:
...     mmif = Mmif(f.read())
... 
>>> for anno in mmif["v_0"].annotations:
...     anno = mmif[anno.id]
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/hmccormick/.local/lib/python3.9/site-packages/mmif/serialize/mmif.py", line 590, in __getitem__
    raise KeyError("ID not found: %s" % item)
KeyError: 'ID not found: to_1'

>>> for anno in mmif["v_0"].annotations:
...     anno = mmif[anno.long_id]

>>> # Works without error on long IDs
```

**Comment by keighrim** [comment]
Not sure this is actually a bug. Although the documentation isn't super clear, 

https://github.com/clamsproject/mmif-python/blob/2a5bffc36ba360e45715bd48c7af07e841717f7a/mmif/serialize/mmif.py#L564-L590

considering 
1. it says it expects _a view-scoped annotation ID_ (short ID)
2. it raises error when two objects with the same ID (when a document and a view have the same id, line 588)
3. annotation IDs are only scoped within a view, so it's much more likely to have ID conflict by querying annotation ID only. 

I think an error when querying with a short ID is somewhat expected behavior. Easy workaround this limitation in the downstream is probably just using `anno.long_id` instead of `anno.id`. 

https://github.com/clamsproject/mmif-python/blob/693972a2868e226453f55b9c42380061ce96d996/mmif/serialize/annotation.py#L131-L135
